language: node_js
node_js:
- '7'
script:
- npm run lint
- npm run cover
- npm run build
after_success: npm run coveralls
deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    tags: true
    repo: daveamit/json-match
