language: node_js
node_js:
- '7'
- '6'
- '6.1'
- '5.11'
script:
- npm run lint
- npm run cover
- npm run build
after_success: npm run coveralls
before_deploy:
- npm run clean && npm run lint && npm run test && npm run build
- cp package.json lib/package.json
- cd lib
deploy:
  provider: npm
  email: daveamit@live.com
  api_key:
    secure: nrGGUJBBaGxwCqoj2sbJMU1QuQKfz5VvxY91nzhPMe0werTx4oLSmoJ8Eijnadi7Ld/nIsHolQ0KPiTvQqjFIiSUbztO4bY7mATqYO5h830tEhpsLqoRadwDFB29cesNoH4ZxigXQMQHZcRoqkRkz9t/Zdn3vhlDYx3YjsOwcx7RCqIG7rcFwrYldUjVNX9MF4oYJUbK/nLhlVyDqU8tVdzozPp0vdaUDWv3xYc/S89OxONJ/4qCpWfnPSZ/4aqd+B5v1OqMgHdOrsFEsfGpWro1XG7diBk9LWyg6OemSoZyV56pAanvpCtwSZ06oKlLs6+nhtia92Hqkb1f+MlR49su1FsklONXKWMCouXm/QxSAill6K8IzZ04R+H+yY2Qkwq2iWt8moZvoZC72QpD3sABzxqffOOBaCMU/BWDgQy1C9Zmar6UViLfveO/8XafLSvbxJq5PcBpz9/Up7MyK4sUTxAwy01pjySyfQDbbEuTQRRa80FVZvyazKNz7fnUU8bn1v2kkS54KRYui3Gl04Zmj5ErMOcyK7jW9hy8TZpN6EB7tJYw7o9dFsjStPK+mW+Ej84gZRrUW4LJVB2YBhHuBHnKwbcIO1taxEHaOBm0x4Ko+YpQYTa55vJ/ynmS4UPvfVYEcwFd36clyipUnOXn4z+5Wva1yEE07063i/k=
  on:
    tags: true
    repo: daveamit/json-match
