language: node_js
node_js:
- '7'
- '6'
- '6.1'
- '5.11'
script:
- npm run lint
- npm run cover
- npm run build
after_success: npm run coveralls
deploy:
  skip_cleanup: true
  provider: script
  script: printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc && npm run clean && npm run lint && npm run test && npm run build && npm run copy-package && cd lib && npm publish
  on:
    tags: true
    repo: daveamit/json-match
